---
title: "analysis"
author: "Chen Mo, Zhixing Wu, Haoyang Yi"
date: "12/10/2021"
output: html_document
---
```{r include = F}
library(tidyverse)
library(survey)
```

```{r}
# recode

data = read.csv("nhanes99_06_NEW.csv")

data =data %>% 
  mutate(RIDRETH1 = case_when(RIDRETH1 == 4 ~ 1,
                              RIDRETH1 == 3 ~ 2,
                              RIDRETH1 %in% c(1,2,5) ~ 3),
         DMDEDUC2 = case_when(DMDEDUC2  == 1 ~ 1,   # 1: Less Than 9th Grade
                              DMDEDUC2 %in% c(2,3,4,5,7,9) ~ 2),
         DMDMARTL = case_when(DMDMARTL == 1 ~ 1,    #1: married
                              DMDMARTL %in% c(2,3,4,5,6,77,99) ~ 2),
         SMQ040 = case_when(SMQ040 %in% c(1,2) ~ 1,
                            SMQ040 %in% c(3,9) ~ 2))
         
data = data %>% 
  mutate(BPQ020 = case_when(BPQ020 == 1 ~ 1,
                            BPQ020 ==2 ~ 2,
                            BPQ020 == 9 ~3),
         BPQ080 = case_when(BPQ080 == 1 ~ 1,
                            BPQ080 ==2 ~ 2,
                            BPQ080 %in% c(7,9) ~3),
         BPQ090A = case_when(BPQ090A == 1 ~ 1,
                            BPQ090A ==2 ~ 2,
                            BPQ090A ==9 ~3))

data = data %>% 
  mutate(MCQ160F = case_when(MCQ160F == 1 ~ 1,
                            MCQ160F ==2 ~ 2,
                            MCQ160F == 9 ~3),
         MCQ160C = case_when(MCQ160C == 1 ~ 1,
                            MCQ160C ==2 ~ 2,
                            MCQ160C %in% c(7,9) ~3),
         MCQ160E = case_when(MCQ160E == 1 ~ 1,
                            MCQ160E ==2 ~ 2,
                            MCQ160E %in% c(7,9) ~3),
         MCQ160L = case_when(MCQ160L == 1 ~ 1,
                            MCQ160L ==2 ~ 2,
                            MCQ160L == 9 ~3))
data = data %>% 
  mutate(DIQ010 = case_when(DIQ010 == 1 ~ 1,
                            DIQ010 ==2 ~ 2,
                            DIQ010 %in% c(3,7,9) ~3),
         DIQ050 = case_when(DIQ050 == 1 ~ 1,
                            DIQ050 ==2 ~ 2,
                            DIQ050 %in% c(7,9) ~3),
         DIQ070 = case_when(DIQ070 == 1 ~ 1,
                            DIQ070 ==2 ~ 2,
                            DIQ070 ==9 ~3))

data$RIAGENDR <- factor(data$RIAGENDR, levels = 1: 2, labels =c("Male", "Female"))
data$RIDRETH1 <- factor(data$RIDRETH1, levels = 1: 3, labels =c("Black", "White", "other"))
data$DMDEDUC2 <- factor(data$DMDEDUC2, levels = 1: 2, labels =c("Less Than 9th Grade", "9th Grade or above"))
data$DMDMARTL <- factor(data$DMDMARTL, levels = 1: 2, labels =c("Married", "Non-Married"))
data$SMQ040 <- factor(data$SMQ040, levels = 1: 2, labels =c("smoked", "Non-smoked"))


data$BPQ020 <- factor(data$BPQ020, levels = 1: 3, labels =c("Yes", "No", "other"))
data$BPQ080 <- factor(data$BPQ080, levels = 1: 3, labels =c("Yes", "No", "other"))
data$BPQ090A <- factor(data$BPQ090A, levels = 1: 3, labels =c("Yes", "No", "other"))

data$MCQ160F <- factor(data$MCQ160F, levels = 1: 3, labels =c("Yes", "No", "other"))
data$MCQ160C <- factor(data$MCQ160C, levels = 1: 3, labels =c("Yes", "No", "other"))
data$MCQ160E <- factor(data$MCQ160E, levels = 1: 3, labels =c("Yes", "No", "other"))
data$MCQ160L <- factor(data$MCQ160L, levels = 1: 3, labels =c("Yes", "No", "other"))

data$DIQ010 <- factor(data$DIQ010, levels = 1: 3, labels =c("Yes", "No", "other"))
data$DIQ050 <- factor(data$DIQ050, levels = 1: 3, labels =c("Yes", "No", "other"))
data$DIQ070 <- factor(data$DIQ070, levels = 1: 3, labels =c("Yes", "No", "other")) 

```

```{r}

data$outcome = NULL
data$outcome[data$LBXGLU>=126] = 1
data$outcome[data$DIQ010=='Yes'] = 1
data$outcome[data$DIQ050=='Yes'] = 1
data$outcome[data$DIQ070=='Yes'] = 1
data$outcome[data$LBXGLU<=126 & data$DIQ010!='Yes'&data$DIQ010!='Yes'&data$DIQ010!='Yes'] = 0
data$outcome = as.factor(data$outcome)
data1 = data %>%
   drop_na(outcome) %>%
   filter(RIDAGEYR>=20) %>%
   filter(MCQ160L!= 'Yes')
# exclusion criteria: no missing value in outcome, age >=20, no history of liver disease.
data1 = data1 %>%
   mutate(age = case_when(RIDAGEYR<=39 ~ 1,
                          RIDAGEYR>=40 & RIDAGEYR <=59 ~2,
                          RIDAGEYR>=60 ~ 3))
data1$age <- factor(data1$age, levels = 1: 3, labels =c("20-39", "40-59", "60 and above"))

data1$hypten = NULL # definition of hypertension is : mean systolic blood pressure
# of 140 mm Hg, a mean diastolic blood pressure of 90 mm Hg OR have been told by doctor

data1$hypten[data1$BPXDAR>=90&data1$BPXSAR>=140] =1
data1$hypten[data1$BPXDAR<=90|data1$BPXSAR<=140] =0
data1$hypten[data1$BPQ020 == 'Yes'] = 1
table(data1$hypten)
data1$hypten = as.factor(data1$hypten)


data1$totalcho = NULL  # Total cholesterol: reporting that a physician had diagnosed that person with high cholesterol OR
# reporting that a physician had advised that person to take cholesterol lowering medications 
data1$totalcho[data1$BPQ080 == 'Yes'|data1$BPQ090 == 'Yes'] = 1
data1$totalcho[data1$BPQ080 != 'Yes'| data1$BPQ090 != 'Yes'] = 0
table(data1$totalcho)
data1$totalcho = as.factor(data1$totalcho)

data1$cardiov = NULL # cardiovascular disease was defined as a self-reported history of coronary heart disease, previous heart attack, or history of stroke. 
data1$cardiov[data1$MCQ160F== 'Yes'|data1$MCQ160C== 'Yes'|data1$MCQ160E== 'Yes']=1
data1$cardiov[data1$MCQ160F!= 'Yes'&data1$MCQ160C!= 'Yes'& data1$MCQ160E!= 'Yes']=0
table(data1$cardiov)
data1$cardiov = as.factor(data1$cardiov)
data1$bilirudin = NULL
data1$bilirudin[data1$LBDSTBSI>=10]=1
data1$bilirudin[data1$LBDSTBSI<=10]=0
table(data1$bilirudin)
data1$bilirudin = as.factor(data1$bilirudin)

# recalculate the weight in 8 yrs
data1$INT8YR = NULL
data1$INT8YR[data1$SDDSRVYR==1|data1$SDDSRVYR==2] = 2/4 * data1$WTINT4YR[data1$SDDSRVYR==1|data1$SDDSRVYR==2]
data1$INT8YR[data1$SDDSRVYR==3|data1$SDDSRVYR==4] = 1/4 * data1$WTINT2YR[data1$SDDSRVYR==3|data1$SDDSRVYR==4]


write.csv(data1, 'analysis.csv')
```

```{r}
# data cleaning
data1 = read.csv("analysis.csv")

data1 = data1 %>% 
   mutate(bmi = case_when (BMXBMI<25 ~ 1,
                           (BMXBMI>=25 & BMXBMI<29) ~ 2,
                           BMXBMI>=30 ~ 3))
data1$bmi <- factor(data1$bmi, levels = 1: 3, labels =c("less than 25", "25-29", "30 and above"))

data1$waist[data1$RIAGENDR=="Male" & data1$BMXWAIST < 102] = "lower"
data1$waist[data1$RIAGENDR=="Male" & data1$BMXWAIST >= 102] = "higher"
data1$waist[data1$RIAGENDR=="Female" & data1$BMXWAIST < 88] = "lower"
data1$waist[data1$RIAGENDR=="Female" & data1$BMXWAIST >= 88] = "higher"
data1$waist = as.factor(data1$waist)

data1$tri[data1$LBXTR < 90] = "low"
data1$tri[data1$LBXTR >= 90] = "high"
data1$tri = as.factor(data1$tri)

data1$al[data1$RIAGENDR=="Male" & data1$ALQ130 > 4] = "heavy consumption"
data1$al[data1$RIAGENDR=="Male" & data1$ALQ130 <= 4] = "moderate or no consumption"
data1$al[data1$RIAGENDR=="Female" & data1$ALQ130 > 3] = "heavy consumption"
data1$al[data1$RIAGENDR=="Female" & data1$ALQ130 <= 3] = "moderate or no consumption"
data1$al = as.factor(data1$al)

```


```{r}
# survey design
dstrat <- svydesign(id = ~SDMVPSU, strata = ~SDMVSTRA, weights = ~INT8YR, data = data1, nest= T)
```


```{r}
# figure 1 
svyhist(~LBDSTBSI,design=dstrat,main="Histogram with kernel density")
den  =svysmooth(~LBDSTBSI, dstrat,bandwidth = 5)
lines(den)
```


```{r}
# age
age = svyby(~bilirudin, ~age, design = dstrat, svymean, na.rm = TRUE)
age
confint(age)

# gender
gender = svyby(~bilirudin, ~factor(RIAGENDR), design = dstrat, svymean, na.rm = TRUE)
gender
confint(gender)

# education
edu = svyby(~bilirudin, ~factor(DMDEDUC2), design = dstrat, svymean, na.rm = TRUE)
edu
confint(edu)

# race
race = svyby(~bilirudin, ~factor(RIDRETH1), design = dstrat, svymean, na.rm = TRUE)
race
confint(race)

# smoke
smoke = svyby(~bilirudin, ~factor(SMQ040), design = dstrat, svymean, na.rm = TRUE)
smoke
confint(smoke)

# alcohol
al = svyby(~bilirudin, ~factor(al), design = dstrat, svymean, na.rm = TRUE)
al
confint(al)

# triclycerides
tri = svyby(~bilirudin, ~factor(tri), design = dstrat, svymean, na.rm = TRUE)
tri
confint(tri)

# waist circumference
waist = svyby(~bilirudin, ~factor(waist), design = dstrat, svymean, na.rm = TRUE)
waist
confint(waist)

# bmi
bmi = svyby(~bilirudin, ~factor(bmi), design = dstrat, svymean, na.rm = TRUE)
bmi
confint(bmi)
```




```{r}
# logistic regression without covariates
model1 <- svyglm(bilirudin ~ factor(hypten) + factor(totalcho) + factor(cardiov) + factor(tri) + factor(al) + factor(bmi) + factor(waist), family=quasibinomial, design=dstrat)
summary(model1)
```

```{r}
# logistic regression with covariates
model2 <- svyglm(bilirudin ~ factor(hypten) + factor(totalcho) + factor(cardiov) + factor(tri) + factor(al) + factor(bmi) + factor(waist) + factor(age) + factor(RIAGENDR) + factor(DMDEDUC2) + factor(RIDRETH1) + factor(SMQ040) + factor(DMDMARTL), family=quasibinomial, design=dstrat)
summary(model2)
```
## additional analysis : bivariate analysis and introducing interaction terms in regression
```{r fig.width=15}
#exploring potential relationship between two covariates in predicting the outcome by bivariate analysis
des = svydesign(ids = ~SDMVPSU, weights = ~INT8YR, strata =  ~SDMVSTRA, nest = T, data = data1)
options( survey.lonely.psu = "adjust" )

plot(density(data1$LBDSTBSI,na.rm = T,adjust = 2))

svyhist(~LBDSTBSI,design=des,main="Histogram with kernel density")

den  =svysmooth(~LBDSTBSI, des,bandwidth = 5)
lines(den)
svyhist(~BMXBMI,design=des,main="Histogram with kernel density")
den  =svysmooth(~BMXBMI, des)
lines(den)

b = svyby(~outcome,~SMQ040+RIDRETH1,design=des,svymean)

barplot(b,beside=F,main="Proportions of Diabete across race and smoke status")
svychisq(~SMQ040+RIDRETH1,des,statistic = 'F') # Rao-Scott F-statistic test shows association between smoke and race. 
c = svyby(~outcome,~age+SMQ040,design=des,svymean)

barplot(c,beside=F,main="Proportions of Diabete across age group and smoke status")

d = svyby(~outcome,~age+RIDRETH1,design=des,svymean)

barplot(d,beside=F,main="Proportions of Diabete across age group and race")

e = svyby(~outcome,~age+RIAGENDR,design=des,svymean)

barplot(e,beside=F,main="Proportions of Diabete across age group and sex")

f = svyby(~outcome,~RIDRETH1+RIAGENDR,design=des,svymean)

barplot(f,beside=F,main="Proportions of Diabete across race and sex")

g = svyby(~outcome,~SMQ040+RIAGENDR,design=des,svymean)

barplot(g,beside=F,main="Proportions of Diabete across smoke status and sex")

h = svyby(~outcome,~age+DMDEDUC2,design=des,svymean)

barplot(h,beside=F,main="Proportions of Diabete across age and education")

i = svyby(~outcome,~age+DMDMARTL,design=des,svymean)

barplot(i,beside=F,main="Proportions of Diabete across age and marrital")

j = svyby(~outcome,~RIDRETH1+DMDEDUC2,design=des,svymean)

barplot(j,beside=F,main="Proportions of Diabete across race and education")
svychisq(~RIDRETH1+DMDEDUC2,des,statistic = 'F') # Rao-Scott F-statistic test shows association between smoke and race. 

k = svyby(~outcome,~RIDRETH1+DMDMARTL,design=des,svymean)

barplot(k,beside=F,main="Proportions of Diabete across race and marrital")



# add interaction terms in covariates adjusted model

model3 <- svyglm(bilirudin ~ factor(hypten) + factor(totalcho) + factor(cardiov) + factor(tri) + factor(al) + factor(bmi) + factor(waist) + factor(age) + factor(RIAGENDR) + factor(DMDEDUC2) + factor(RIDRETH1) + factor(SMQ040) + factor(DMDMARTL)+factor(SMQ040)*factor(RIDRETH1), family=quasibinomial, design=dstrat)

summary(model3)

regTermTest(model3, ~bilirudin ~ factor(hypten) + factor(totalcho) + factor(cardiov) + factor(tri) + factor(al) + factor(bmi) + factor(waist) + factor(age) + factor(RIAGENDR) + factor(DMDEDUC2) + factor(RIDRETH1) + factor(SMQ040) + factor(DMDMARTL), method="LRT", df=1) # Rao-Scott test based on the estimated log likelihood ratio ----------p-value = 0.061 which indicates model 3 considering interaction between race and smoke is not better than the smaller model 2

model4 <- svyglm(bilirudin ~ factor(hypten) + factor(totalcho) + factor(cardiov) + factor(tri) + factor(al) + factor(bmi) + factor(waist) + factor(age) + factor(RIAGENDR) + factor(DMDEDUC2) + factor(RIDRETH1) + factor(SMQ040) + factor(DMDMARTL)+factor(DMDEDUC2)*factor(RIDRETH1), family=quasibinomial, design=dstrat)

summary(model4)

regTermTest(model4, ~bilirudin ~ factor(hypten) + factor(totalcho) + factor(cardiov) + factor(tri) + factor(al) + factor(bmi) + factor(waist) + factor(age) + factor(RIAGENDR) + factor(DMDEDUC2) + factor(RIDRETH1) + factor(SMQ040) + factor(DMDMARTL), method="LRT", df=1) # Rao-Scott test based on the estimated log likelihood ratio ----------p-value = 0.0418 < 0.05 which indicates model 4 considering interaction between race and education is  better than the smaller model 2

```